### ISSUE TITLE
Cannot read property 'startTime' of undefined

### ISSUE THREAD

**Issue by eitankw** [ericduran/chromeHAR#62]
Happens with chromium Version 36.0.1985.125 Ubuntu 14.04 (283153)

console:
TypeError: Cannot read property 'startTime' of undefined
    at Object.<anonymous> (http://ericduran.github.io/chromeHAR/js/controllers.js:110:47)
    at Function.x.extend.each (http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js:4:4575)
    at Object.$scope.updateHar (http://ericduran.github.io/chromeHAR/js/controllers.js:108:9)
    at http://ericduran.github.io/chromeHAR/js/controllers.js:247:22
    at Object.g.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular.min.js:104:502)
    at Object.g.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular.min.js:105:102)
    at FileReader.reader.onload (http://ericduran.github.io/chromeHAR/js/controllers.js:246:20) 

Thanks!

**Comment by kajmagnus79** [comment]
Happens to me too. Chrome 44.0.x on Windows.

```
TypeError: Cannot read property 'startTime' of undefined
    at Object.<anonymous> (controllers.js:110)
    at Function.x.extend.each (jquery.min.js:4)
    at Object.cH.controller.$scope.updateHar (controllers.js:108)
    at controllers.js:247
    at Object.$get.g.$eval (angular.min.js:104)
    at Object.$get.g.$apply (angular.min.js:105)
    at FileReader.cH.controller.$scope.$watch.reader.onload (controllers.js:246)
```

I found this: https://chrome.google.com/webstore/detail/http-archive-viewer/ebbdbdmhegaoooipfnjikefdpeoaidml/related?hl=en
 — it works
